Use the same subprotocol negotiation mechanism as HTTP/3
ietf-wg-webtrans/draft-ietf-webtrans-http2 pull request #112
Opened 2024-05-14 19:35 UTC by ekinnear

Use the same subprotocol negotiation mechanism as HTTP/3

Fixes #108

2024-05-14 20:43 UTC, DavidSchinazi commented on draft-ietf-webtrans-http2.md
> +Both `WebTransport-Subprotocols-Available` and `WebTransport-Subprotocol` are
Should we instead point to the h3 draft for the definition of the fields? It feels weird to redefine them here

2024-05-14 22:44 UTC, martinthomson requested changes
Let's refer to h3 for the definitions.

2024-05-23 19:39 UTC, DavidSchinazi approved these changes

2024-07-09 22:12 UTC, martinthomson approved these changes

2024-07-21 22:02 UTC, merged